stages:
  explore_data:
    cmd: python src/data_exploration.py data/data.csv
    deps:
      - src/data_exploration.py
      - data/data.csv
    outs:
      - data/exploration_results

  preprocess_data:
    cmd: python src/data_preprocessing.py data/data.csv
    deps:
      - src/data_preprocessing.py
      - data/data.csv
    outs:
      - data/processed

  automl_training:
    cmd: python src/automl_training.py
    deps:
      - src/automl_training.py
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
    outs:
      - models/best_model.py
      - models/best_model.joblib

  interpret_results:
    cmd: python src/interpret_results.py
    deps:
      - src/interpret_results.py
      - models/best_model.joblib
      - data/processed/X_test.csv
      - data/processed/y_test.csv
    outs:
      - results/interpretation_results.txt
      - results/metrics.csv
      - results/metrics.md
      - results/feature_importances.csv


  hyperparameter_optimization:
    cmd: python src/hyperparameter_optimization.py
    deps:
      - src/hyperparameter_optimization.py
      - data/processed/X_train.csv
      - data/processed/y_train.csv
    outs:
      - results/best_hyperparameters.joblib
      - results/optuna_best_params.txt
      - results/optuna_optimization_history.html
      - results/optuna_param_importance.html