stages:
  explore_data:
    cmd: python src/data_exploration.py data/data.csv
    deps:
      - src/data_exploration.py
      - data/data.csv
    outs:
      - data/exploration_results

  preprocess_data:
    cmd: python src/data_preprocessing.py data/data.csv
    deps:
      - src/data_preprocessing.py
      - data/data.csv
    outs:
      - data/processed

  automl_training:
    cmd: python src/automl_training.py
    deps:
      - src/automl_training.py
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
    outs:
      - models/best_model.py
      - models/best_model.joblib