train:
  test_size: 0.2
  random_state: 42
  alpha: 0.1

preprocessing:
  target: price
  features: [area, bedrooms, bathrooms, stories, parking]

automl:
  generations: 5 
  population_size: 20  
  random_state: 42 
